config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcomes#index'

  get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :personal_chatrooms
  
  resources :messages
  resources :personal_messages

  resources :welcomes, only: [:index] do
  	get :search_users, on: :collection
    get :friends, on: :collection
	end
	resources :friend_requests do
    get :accept, on: :member    
  end
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord

  default_scope { where(chat_type: 'Group') }

  has_many :messages, dependent: :destroy
  has_many :users, through: :messages

  validates :topic, presence: true, uniqueness: true, case_sensitive: false
  
  before_validation :sanitize, :slugify

  def to_param
    self.slug
  end

  def slugify
    self.slug = self.topic.downcase.gsub(" ", "-")
  end

  def sanitize
    self.topic = self.topic.strip
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all
  end

  def new
    if request.referrer.split("/").last == "chatrooms"
      flash[:notice] = nil
    end
    @chatroom = Chatroom.new
  end

  def edit
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      respond_to do |format|
        format.html { redirect_to @chatroom }
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chatroom with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'} 
      end
    end
  end

  def update
    chatroom = Chatroom.find_by(slug: params[:slug])
    chatroom.update(chatroom_params)
    redirect_to chatroom
  end

  def show
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @message = Message.new
  end

  private

    def chatroom_params
      params.require(:chatroom).permit(:topic)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_chatroom.html.erb
<li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>

app/views/chatrooms/_chatroom_form.html.erb
<div class="chatroom-form">
  <%= form_for chatroom, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">group name:</span>
      <%= f.text_field :topic, class: "form-control"%>
    </div>
    <%= f.submit 'Create Group', class: "btn btn-primary", id: "create-chatroom" %>
  <% end %>
</div>

app/views/chatrooms/chatroom_error.js.erb
$("input#chatroom_topic").val(" ");
$("#chatroom-errors").html("<br><%=j render partial: 'layouts/flash_errors', locals: {flash: flash}%>");

app/views/chatrooms/create.js.erb
$("input#chatroom_topic").val(" ")
$("#chatroom-errors").html(" ")
$("#chatroom-index").append('<li><%= link_to @chatroom.topic, chatroom_path(@chatroom) %></li>')

app/views/chatrooms/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatroom-title">
  <h1 class= 'title'>Groups</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="chatrooms">
  <div id="chatroom-errors">  
  </div>
    <ul id="chatroom-index"> 
    </ul>
  <div class="well">
    <% if @chatrooms.any? %>
        <%= render @chatrooms%>
    <%else %>

      <p>Be the first one to make a group!</p>
    <% end %>
  </div>
</div>

app/views/chatrooms/new.html.erb
<div class="row col-md-8 col-md-offset-2">

  <h1 class="center">Create a Group</h1>
    <div class="well">
      <div class="chatroom-form">
        <%= form_for @chatroom do |f| %>
          <div class="input-group">
            <span class="input-group-addon">group name:</span>
            <%= f.text_field :topic, class: "form-control"%>
          </div>
          <%= f.submit 'Create Group', class: "btn btn-primary", id: "create-chatroom" %>
        <% end %>
      </div>
    </div>

    <%= render partial: 'layouts/flash_errors'%>
</div>

app/views/chatrooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <% if @chatroom.is_a?(PersonalChatroom) %>
    <% if @chatroom.first_user_id == current_user.id %>
      <h1 class='title'><%= @chatroom.second_user.full_name %></h1>
    <% else %>
      <h1 class='title'><%= @chatroom.first_user.full_name %></h1>
    <% end %>
  <% else %>
    <h1 class='title'><%= @chatroom.topic %></h1>
  <% end %>
  <div class="panel panel-default">
    <% messages = @chatroom.is_a?(PersonalChatroom) ? @chatroom.personal_messages : @chatroom.messages %>
    <% if messages.any? %>
      <div class="panel-body" id="messages">
        <%= render partial: 'messages/message', collection: messages.order(:created_at)%>
      </div>
    <%else%>
      <div class="panel-body hidden" id="messages">
      </div>
    <%end%>
  </div>
  <%= render partial: 'messages/message_form', locals: { message: @message, chatroom: @chatroom}%>
</div>