config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcomes#index'

  get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :personal_chatrooms
  
  resources :messages
  resources :personal_messages

  resources :welcomes, only: [:index] do
  	get :search_users, on: :collection
    get :friends, on: :collection
	end
	resources :friend_requests do
    get :accept, on: :member    
  end
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
	   @chatrooms = Chatroom.all
	   @personal_chats = PersonalChatroom.private_chats_for(current_user.id)     
  end

  def search_users
  	if params[:first_name].present? || params[:last_name].present?
  		@users = User.search_by_full_name(params[:first_name], params[:last_name])
  	end
	end

  def friends
    @friends = current_user.friends
  end

end

app/views/welcomes/friends.html.slim
.form.color-white
	- @friends.each do |friend|
		.row
			.col-sm-4
				= friend.full_name
			.col-sm-4
				=link_to 'Send Message', personal_chatroom_path(friend.id)
			.col-sm-4
				=link_to 'Un friend', friend_request_path(friend.id), method: :delete

app/views/welcomes/index.html.slim
.row.col-md-8.col-md-offset-2#chatroom-title
  h1.title= 'Groups'

.row.col-md-8.col-md-offset-2#chatrooms
  #chatroom-errors
    ul#chatroom-index
  .well
    - if @chatrooms.any?
      = render @chatrooms
    - else
      p= "Be the first one to make a group!"

app/views/welcomes/search_users.js.erb
<% if @users.present? %>
 $('.users').html("<%=j render :partial => 'users/index' %>");
<% else %>
 $('.users').html("<div class='form color-white'>No result found, please try other keywords</div>");
<% end %>