config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcomes#index'

  get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :personal_chatrooms
  
  resources :messages
  resources :personal_messages

  resources :welcomes, only: [:index] do
  	get :search_users, on: :collection
    get :friends, on: :collection
	end
	resources :friend_requests do
    get :accept, on: :member    
  end
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/views/layouts/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
      <% flash.notice.each do |type, messages|%>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%messages.each do |msg|%>
          <%=type%> <%=msg%>
        <%end%>
      <%end%>
  </div>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Live Chat", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render partial: 'layouts/navbar_links' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <% if current_user %>
    <li>
      <%= link_to "New Group", new_chatroom_path%>
    </li>
    <li>
      <%= link_to "Groups", chatrooms_path %>
    </li>
    <% if user_friend_requests.pending.present? %>
      <li>
      <%= link_to 'Friend Request', friend_requests_path%>
      </li>
    <% end %>
    <% if current_user.friends.present? %>
      <li>
      <%= link_to 'Friends', friends_welcomes_path%>
      </li>
    <% end %>
    <li class='space-10 vspace-10'>
      <%= render 'shared/search' %>
    </li>
  <% end %>
  
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><%= link_to "Profile", edit_user_registration_path %></li>
    <li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
  <% else %>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <li><%= link_to "Log In", new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Live Chat</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css" />
  </head>

  <body>
   <a class="github-fork-ribbon right-bottom fixed" href="https://www.linkedin.com/in/ganesh-navale-258aa6111/" title="Follow me on LinkedIn">Ganesh Navale</a>
  <%= render partial: 'layouts/navbar' %>
  <div class='users'>
  </div>
  <div class="container">
    <% if notice %>
      <p class="alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert-alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>